ethercat_master:
  time_step:                          0.000250
  update_rate_too_low_warn_threshold: 10

ethercat_devices:
  - type:               Opus
    name:               ZeroErr Driver
    configuration_file: device_configurations/opus.yaml
    ethercat_bus:       enp2s0
    ethercat_address:   1